### ISSUE TITLE
Why not the same?

### ISSUE THREAD

**Issue by myaaghubi** [ShiJess/Link.WPF.Toolkit#3]
In the repo:
https://github.com/ShiJess/Link.WPF.Toolkit/blob/d07b4970ceff3642146b4ed467c225bb3d09b693/src/Link.WPF.Toolkit/IPAddrBox/IPAddrBox.cs#L251-L259

In the Nuget package:
`public bool IsValidInput()
		{
			return this.IsValidIP() || string.IsNullOrWhiteSpace(this.IPTextA.Text + this.IPTextB.Text + this.IPTextC.Text + this.IPTextD.Text);
		}`

There is a logical difference between that two methods, why the Nuget package is not the same as the repo?

**Comment by ShiJess** [comment]
I use ILSpy check it and they are consistent.
Maybe,you should check your decompiler tool.

**Comment by myaaghubi** [comment]
Yeh, you right, it looks like the problem is on the decompiler.
